president = {
    "Afghanistan":  "Ashraf Ghani",
    "Albania": "Ilir Meta",
    "Algeria": "Abdelmadjid Tebboune",
    "Andorra": "Xavier Espot Zamora",
    "Angola": "João Lourenço",
    "Antigua and Barbuda": " Gaston Browne",
    "Argentina": "Alberto Fernández",
    "Armenia": "Armen Sarkissian",
    "Australia": " Scott Morrison",
    "Austria": "Alexander Van der Bellen",
    "Azerbaijan": "Ilham Aliyev",
    "The Bahamas": "Hubert Minnis",
    "Bahrain": "Prince Khalifa bin Salman Al Khalifa",
    "Bangladesh": " Abdul Hamid",
    "Barbados": "Mia Mottley",
    "Belgium": "Sophie Wilmès",
    "Belize": "Dean Barrow",
    "Benin": " Patrice Talon",
    "Bhutan": "Lotay Tshering",
    "Bolivia": "Jeanine Áñez",
    "Bosnia and Herzegovina": "Valentin Inzko",
    "Botswana": "Mokgweetsi Masisi",
    "Brazil": "Jair Bolsonaro",
    "Brunei": "Hassanal Bolkiah",
    "Bulgaria": "Rumen Radev",
    "Burkina Faso": "Roch Marc Christian Kaboré",
    "Burundi": "Pascal Nyabenda",
    "Cambodia": "Hun Sen",
    "Cameroon": "Paul Biya",
    "Canada": "Julie Payette",
    "Cape Verde": "Jorge Carlos Fonseca",
    "Central African Republic": "Faustin-Archange Touadéra",
    "Chad": "Idriss Déby",
    "Chile": "Sebastián Piñera",
    "China": "Xi Jinping",
    "Colombia": "Iván Duque",
    "Comoros": "Azali Assoumani",
    "Congo": "Félix Tshisekedi",
    "Costa Rica": "Carlos Alvarado Quesada",
    "Croatia": "Zoran Milanović",
    "Cuba": "Miguel Díaz-Canel",
    "Cyprus": "Nicos Anastasiades",
    "Czech Republic": "Miloš Zeman",
    "Denmark": "Mette Frederiksen",
    "Djibouti": "Ismaïl Omar Guelleh",
    "Dominica": "Charles Savarin",
    "Dominican Republic": "Danilo Medina",
    "East Timor": "Francisco Guterres",
    "Ecuador": "Lenín Moreno",
    "Egypt": "Abdel Fattah el-Sisi",
    "El Salvador": "Nayib Bukele",
    "Equatorial Guinea": "Teodoro Obiang Nguema Mbasogo",
    "Eritrea": "Isaias Afwerki",
    "Estonia": "Kersti Kaljulaid",
    "Eswatini": "Ambrose Mandvulo Dlamini",
    "Ethiopia": "Sahle-Work Zewde",
    "Fiji": "ioji Konrote",
    "Finland": "Sauli Niinistö",
    "France": "Emmanuel Macron",
    "Gabon": "Ali Bongo Ondimba",
    "Gambia": "Adama Barrow",
    "Georgia": "Salome Zourabichvili",
    "Germany": "Frank-Walter Steinmeier",
    "Ghana": "Nana Akufo-Addo",
    "Greece": "Katerina Sakellaropoulou",
    "Grenada": "Dame Cécile La Grenade",
    "Guatemala": "Alejandro Giammattei",
    "Guinea": "Alpha Condé[",
    "Guinea-Bissau": "Umaro Sissoco Embaló",
    "Guyana": "David A. Granger",
    "Haiti": "Jovenel Moïse",
    "Honduras": "Juan Orlando Hernández",
    "Hungary": "János Áder",
    "Iceland": "Guðni Th. Jóhannesson",
    "India": "Ram Nath Kovind",
    "Indonesia": "Joko Widodo",
    "Iran": "Ali Khamenei",
    "Iraq": "Barham Salih",
    "Ireland": "Michael D. Higgins",
    "Israel": "Reuven Rivlin",
    "Italy": "Sergio Mattarella",
    "Ivory Coast": "Alassane Ouattara",
    "Jamaica": "Sir Patrick Allen",
    "Japan": "Shinzō Abe",
    "Jordan": "Omar Razzaz",
    "Kazakhstan": "Nursultan Nazarbayev",
    "Kenya": "Uhuru Kenyatta",
    "Kiribati": "Taneti Maamau",
    "Kuwait": "Sheikh Sabah Al-Khalid Al-Sabah",
    "Kyrgyzstan": "Sooronbay Jeenbekov",
    "Laos": "Bounnhang Vorachith",
    "Latvia": "Egils Levits",
    "Lebanon": "Michel Aoun",
    "Lesotho": "Moeketsi Majoro",
    "Liberia": "George Weah",
    "Libya": "Fayez al-Sarraj",
    "Liechtenstein": "Adrian Hasler",
    "Lithuania": "Gitanas Nausėda",
    "Luxembourg": "Xavier Bettel",
    "Madagascar": "Andry Rajoelina",
    "Malawi": "Peter Mutharika",
    "Malaysia": "Muhyiddin Yassin",
    "Maldives": "Ibrahim Mohamed Solih",
    "Mali": "Ibrahim Boubacar Keïta",
    "Malta": "George Vella",
    "Marshall Islands": "David Kabua",
    "Mauritania": "Mohamed Ould Ghazouani",
    "Mauritius": "Prithvirajsing Roopun",
    "Mexico": "Andrés Manuel López Obrador",
    "Federated States of Micronesia": "David W. Panuelo",
    "Moldova": "Igor Dodon",
    "Monaco": "lbert II",
    "Mongolia": "Mongolia",
    "Montenegro": "Milo Đukanović",
    "Morocco": "Saadeddine Othmani",
    "Mozambique": "Filipe Nyusi",
    "Myanmar": "Win Myint",
    "Namibia": "Hage Geingob",
    "Nauru": "Lionel Aingimea",
    "Nepal": "Bidhya Devi Bhandari",
    "Netherlands": "Mark Rutte",
    "New Zealand": "Dame Patsy Reddy",
    "Nicaragua": "Daniel Ortega",
    "Niger": "Mahamadou Issoufou",
    "Nigeria": "Muhammadu Buhari",
    "North Korea": "Kim Jong-un",
    "North Macedonia": "Stevo Pendarovski",
    "Norway": "Erna Solberg",
    "Oman": "Haitham bin Tariq",
    "Pakistan": "Pakistan",
    "Palau": "Thomas Remengesau Jr",
    "Palestine": "Mahmoud Abbas",
    "Panama": "Laurentino Cortizo",
    "Papua New Guinea": "Sir Bob Dadae",
    "Paraguay": "Mario Abdo Benítez",
    "Peru": "Martín Vizcarra",
    "Philippines": "Rodrigo Duterte",
    "Poland": "Andrzej Duda",
    "Portugal": "Marcelo Rebelo de Sousa",
    "Qatar": "Khalid bin Khalifa bin Abdul Aziz Al Thani",
    "Romania": "Klaus Iohannis",
    "Russia": "Vladimir Putin",
    "Rwanda": "Paul Kagame",
    'Saint Kitts and Nevis': "Sir Tapley Seaton",
    "Saint Lucia": "Sir Neville Cenac",
    "Saint Vincent and the Grenadines": "Dame Susan Dougan",
    'Samoa': "Va'aletoa Sualauvi II",
    "San Marino": "Alessandro Mancini",
    "São Tomé and Príncipe": "Evaristo Carvalho",
    "Saudi Arabia": "Jorge Bom Jesus",
    "Senegal": "Aleksandar Vučić",
    "Seychelles": "Danny Faure",
    "Sierra Leone": "Julius Maada Bio",
    "Singapore": "Halimah Yacob",
    "Slovakia": "Zuzana Čaputová",
    "Slovenia": "Borut Pahor",
    "Solomon Islands": "Sir David Vunagi",
    "Somalia": "Mohamed Abdullahi Mohamed",
    "South Africa": "Cyril Ramaphosa",
    "South Korea": "Moon Jae-in",
    "South Sudan": "Salva Kiir Mayardit",
    "Spain": "Pedro Sánchez",
    "Sri Lanka": "Gotabaya Rajapaksa",
    "Sudan": "Abdel Fattah al-Burhan",
    "Suriname": "Dési Bouterse",
    "Sweden": "Stefan Löfven",
    "Switzerland": "Simonetta Sommaruga",
    "Syria": "Bashar al-Assad",
    "Tajikistan": "Emomali Rahmon",
    "Tanzania": "John Magufuli",
    "Thailand": "Prayut Chan-o-cha",
    "Togo": "Faure Gnassingbé",
    "Tonga": "Pōhiva Tu'i'onetoa",
    "Trinidad and Tobago": "Paula-Mae Weekes",
    "Tunisia": "Kaïs Saïed",
    "Turkey": "Recep Tayyip Erdoğan",
    "Turkmenistan": "Gurbanguly Berdimuhamedow",
    "Tuvalu": "Sir Iakoba Italeli",
    "Uganda": "Yoweri Museveni",
    "Ukraine": "Volodymyr Zelensky",
    "United Arab Emirates": "Sheikh Khalifa bin Zayed Al Nahyan	",
    "United Kingdom": "Boris Johnson",
    "United States": "Donald Trump",
    "Uruguay": "Luis Lacalle Pou",
    "Uzbekistan": "Shavkat Mirziyoyev",
    "Vanuatu": "Tallis Obed Moses",
    "Vatican City": "Cardinal Giuseppe Bertello",
    "Venezuela": "Nicolás Maduro",
    "Vietnam": "Nguyễn Phú Trọng",
    "Yemen": "Abdrabbuh Mansur Hadi",
    "Zambia": "Edgar Lungu",
    "Zimbabwe": "Emmerson Mnangagwa"
}
